### ISSUE TITLE
OS specific Install

### ISSUE THREAD

**Issue by JerryHamm** [weather-eye/weathereye#4]
### Description

- Investigate using [Ansible facts](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html#ansible-facts-distribution) to determine OS type, distribution and version
- The Install may vary depending on the OS being installed on. Initially we may only support a single OS/distribution and version
- If the user's OS is not currently support they should receive a message: "{detected_os} is currently not supported. See docs.weathereye.org for supported operating systems"

**Comment by isedwards** [comment]
Closed by #10
